# Generated by Django 4.0.4 on 2024-05-14 11:51

from django.db import migrations, models
import django.db.models.deletion
import epigraphy.models
import storages.backends.s3


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IconographicElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Monument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text=' Site', max_length=100)),
                ('type', models.CharField(blank=True, choices=[('Castle', 'Castle'), ('Lintel', 'Lintel')], max_length=20, null=True)),
                ('three_dimensional_URL', models.URLField(blank=True, max_length=100, null=True)),
                ('three_360_URL', models.URLField(blank=True, max_length=100, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('long', models.FloatField(blank=True, null=True)),
                ('location', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('bibliography', models.TextField(blank=True, default=None, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Sites',
            },
        ),
        migrations.CreateModel(
            name='Epigraphy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the ID', max_length=100)),
                ('short_name', models.CharField(max_length=100)),
                ('image_1', models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to=epigraphy.models.photos)),
                ('image_2', models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to=epigraphy.models.photos)),
                ('image_3', models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to=epigraphy.models.photos)),
                ('image_4', models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to=epigraphy.models.photos)),
                ('image_5', models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to=epigraphy.models.photos)),
                ('image_6', models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to=epigraphy.models.photos)),
                ('image_7', models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to=epigraphy.models.photos)),
                ('image_8', models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to=epigraphy.models.photos)),
                ('image_9', models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to=epigraphy.models.photos)),
                ('image_10', models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to=epigraphy.models.photos)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('past_location', models.CharField(blank=True, max_length=50, null=True)),
                ('current_location', models.CharField(blank=True, max_length=50, null=True)),
                ('object_type', models.CharField(blank=True, choices=[('anchor', 'anchor'), ('ring', 'ring'), ('atlar', 'altar'), ('slab', 'slab'), ('relief', 'relief')], max_length=50, null=True)),
                ('state_of_preservation', models.CharField(blank=True, choices=[('Epigraphic_fragments_which_can_be_only_partly_joined', 'Epigraphic fragments, which can be only partly joined'), ('incomplete', 'incomplete'), ('probably_complete', 'probably complete'), ('atlar', 'altar'), ('slab', 'slab'), ('broken', 'Broken')], max_length=100, null=True)),
                ('type_of_writing', models.CharField(blank=True, choices=[('inked', 'Inked'), ('engraved', 'Engraved'), ('inlaid_or_embossed', 'Inlaid or Embossed'), ('damascened', 'Damascened'), ('channelled', 'Channelled'), ('metal_letters_applied', 'Metal Letters Applied'), ('relief', 'Relief'), ('moulded', 'Moulded'), ('scratched', 'Scratched'), ('painted', 'Painted'), ('impressed dots', 'Impressed Dots'), ('incised', 'Incised'), ('impressed', 'Impressed'), ('inscribed_on_a_soft_surface', 'Inscribed on a Soft Surface'), ('perforated', 'Perforated'), ('mosaic', 'Mosaic'), ('punched', 'Punched'), ('Other', 'Other'), ('unknown', 'Unknown')], max_length=50, null=True)),
                ('language', models.CharField(blank=True, choices=[('Latin', 'Latin'), ('Greek', 'Greek'), ('Bilingual (Latin-Greek)', 'Bilingual (Latin-Greek)'), ('Italian', 'Italian'), ('Other', 'Other')], max_length=50, null=True)),
                ('type_of_inscription', models.CharField(blank=True, choices=[('Unknown', 'Unknown'), ('Law_official_text', 'Law / official text'), ('Honorary', 'Honorary'), ('Building (public or private)', 'Building (public or private)'), ('Religious', 'Religious'), ('Funerary', 'Funerary')], max_length=50, null=True)),
                ('promoter', models.CharField(blank=True, choices=[('Venetian_aristocrat', 'Venetian aristocrat'), ('Venetian_state', 'Venetian State'), ('Cypriot', 'Cypriot')], max_length=50, null=True)),
                ('material', models.CharField(blank=True, choices=[('Other', 'Other'), ('Silver', 'Silver'), ('Ivory', 'Ivory'), ('Bronze', 'Bronze'), ('Wax', 'Wax'), ('Iron', 'Iron'), ('Plaster', 'Plaster'), ('Wood', 'Wood'), ('Fresh_mortar', 'Fresh mortar'), ('Marble', 'Marble'), ('Mosaic', 'Mosaic'), ('Gold', 'Gold'), ('Stone', 'Stone'), ('Lead', 'Lead'), ('Unknown', 'Unknown'), ('Pottery', 'Pottery'), ('Glass', 'Glass'), ('metamorphic limestone', 'Metamorphic limestone'), ('marble and limestone', 'Marble and limestone')], max_length=50, null=True)),
                ('specific_material', models.CharField(blank=True, max_length=100, null=True)),
                ('administrative_district', models.CharField(blank=True, choices=[('Famagusta (Αμμόχωστος; Gazimağusa)', 'Famagusta (Αμμόχωστος; Gazimağusa)'), ('Kyrenia (Κερύvεια; Girne)', 'Kyrenia (Κερύvεια; Girne)'), ('Larnaca (Λάρνακα; Larnaka)', 'Larnaca (Λάρνακα; Larnaka)'), ('Limassol (Λεμεσός; Leymosun)', 'Limassol (Λεμεσός; Leymosun)'), ('Nicosia (Λευκωσία; Lefkoşa)', 'Nicosia (Λευκωσία; Lefkoşa)'), ('Paphos (Πάφος; Baf)', 'Paphos (Πάφος; Baf)')], max_length=50, null=True)),
                ('height', models.CharField(blank=True, max_length=100, null=True)),
                ('width', models.CharField(blank=True, max_length=100, null=True)),
                ('depth_diameter', models.CharField(blank=True, max_length=100, null=True)),
                ('letter_heights', models.CharField(blank=True, max_length=100, null=True)),
                ('motivation', models.CharField(blank=True, max_length=100, null=True)),
                ('day', models.CharField(blank=True, max_length=100, null=True)),
                ('month', models.CharField(blank=True, max_length=100, null=True)),
                ('year_from', models.CharField(blank=True, max_length=100, null=True)),
                ('year_to', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('bibliography', models.TextField(blank=True, default=None, null=True)),
                ('transcription_interpreted', models.TextField(blank=True, default=None, null=True)),
                ('transcription_diplomatic', models.TextField(blank=True, default=None, null=True)),
                ('translation', models.TextField(blank=True, default=None, null=True)),
                ('apparatus', models.TextField(blank=True, default=None, null=True)),
                ('full_epidoc_xml', models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to=epigraphy.models.files)),
                ('RTI_URL', models.URLField(blank=True, max_length=100, null=True)),
                ('three_dimensional_URL', models.URLField(blank=True, max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('iconographic_elements', models.ManyToManyField(blank=True, to='epigraphy.iconographicelement')),
                ('place', models.ForeignKey(help_text='Corresponding to Site', null=True, on_delete=django.db.models.deletion.SET_NULL, to='epigraphy.monument')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
            },
        ),
    ]
