# Generated by Django 4.0.4 on 2024-05-14 12:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epigraphy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epigraphy',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True),
        ),
    ]
