# Generated by Django 4.0.4 on 2024-05-14 12:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epigraphy', '0002_alter_epigraphy_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epigraphy',
            name='apparatus',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='epigraphy',
            name='bibliography',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='epigraphy',
            name='transcription_diplomatic',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='epigraphy',
            name='transcription_interpreted',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='epigraphy',
            name='translation',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True),
        ),
    ]
