# Generated by Django 4.0.4 on 2024-05-14 12:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epigraphy', '0003_alter_epigraphy_apparatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monument',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True),
        ),
    ]
