# Generated by Django 4.0.4 on 2024-05-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epigraphy', '0005_alter_monument_bibliography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epigraphy',
            name='administrative_district',
            field=models.CharField(blank=True, choices=[('famagusta_αμμόχωστος_gazimağusa', 'Famagusta - Αμμόχωστος - Gazimağusa'), ('kyrenia_κερύvεια_girne', 'Kyrenia - Κερύvεια - Girne'), ('larnaca_λάρνακα_larnaka', 'Larnaca - Λάρνακα - Larnaka'), ('limassol_λεμεσός_leymosun', 'Limassol - Λεμεσός - Leymosun'), ('nicosia_λευκωσία_lefkoşa', 'Nicosia - Λευκωσία - Lefkoşa'), ('paphos_πάφος_baf', 'Paphos - Πάφος - Baf')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='epigraphy',
            name='language',
            field=models.CharField(blank=True, choices=[('latin', 'Latin'), ('greek', 'Greek'), ('bilingual_latin_greek', 'Bilingual Latin-Greek'), ('italian', 'Italian'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='epigraphy',
            name='material',
            field=models.CharField(blank=True, choices=[('bronze', 'Bronze'), ('fresh_mortar', 'Fresh mortar'), ('silver', 'Silver'), ('gold', 'Gold'), ('wax', 'Wax'), ('pottery', 'Pottery'), ('ivory', 'Ivory'), ('iron', 'Iron'), ('stone', 'Stone'), ('wood', 'Wood'), ('marble', 'Marble'), ('mosaic', 'Mosaic'), ('lead', 'Lead'), ('plaster', 'Plaster'), ('glass', 'Glass'), ('other', 'Other'), ('unknown', 'Unknown')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='epigraphy',
            name='object_type',
            field=models.CharField(blank=True, choices=[('amphora', 'amphora'), ('amphora_cap', 'amphora cap'), ('bottle', 'bottle'), ('relief', 'relief'), ('anchor', 'anchor'), ('antefix', 'antefix'), ('altar', 'altar'), ('sepulchral_altar', 'sepulchral altar'), ('fresh_mortar', 'fresh mortar'), ('weapon', 'weapon'), ('helmet', 'helmet'), ('shot', 'shot'), ('breastplate', 'breastplate'), ('sword', 'sword'), ('base_pedestal', 'base/pedestal'), ('column_base', 'column base'), ('base_for_a_sacred_donation', 'base for a sacred donation'), ('screen', 'screen'), ('candlestick', 'candlestick'), ('urn', 'urn'), ('cippus', 'cippus'), ('centurial_cippus', 'centurial cippus'), ('aqueduct_cippus', 'aqueduct cippus'), ('fluvial_cippus', 'fluvial cippus'), ('milestone', 'milestone'), ('pomerium_cippus', 'pomerium cippus'), ('terminal_cippus', 'terminal cippus'), ('key', 'key'), ('spoon', 'spoon'), ('collar', 'collar'), ('pack_for_eye_medication_spread_using_a_signaculum_oculariorum', 'pack for eye medication, spread using a signaculum oculariorum'), ('column_shaft', 'column shaft'), ('statue_base', 'statue base'), ('crown', 'crown'), ('clay_seal_imprint', 'clay seal imprint'), ('barrel', 'barrel'), ('barrel_stave', 'barrel stave'), ('jar', 'jar'), ('diptych', 'diptych'), ('architrave', 'architrave'), ('matrix', 'matrix'), ('dice_box', 'dice box'), ('gem', 'gem'), ('step', 'step'), ('amphitheatre_s_steps', 'amphitheatre’s steps'), ('theatre_s_steps', 'theatre’s steps'), ('herm', 'herm'), ('timepiece', 'timepiece'), ('bust', 'bust'), ('garment_all_types_of_clothes', 'garment/all types of clothes'), ('footwear', 'footwear'), ('belt', 'belt'), ('basin', 'basin'), ('brick', 'brick'), ('balance_scales', 'balance, scales'), ('oil_lamp', 'oil-lamp'), ('ingot', 'ingot'), ('table', 'table'), ('measuring_table_volume', 'measuring table, volume'), ('measuring_table_space', 'measuring table, space'), ('measure', 'measure'), ('millstone', 'millstone'), ('personal_or_clothing_ornament', 'personal or clothing ornament'), ('ring', 'ring'), ('bracelet', 'bracelet'), ('buckle', 'buckle'), ('earring', 'earring'), ('necklace_torque', 'necklace, torque'), ('mortar', 'mortar'), ('escavated_shrine', 'escavated shrine'), ('block_with_holes_for_cinerary_urns', 'block with holes for cinerary urns'), ('pendent', 'pendent'), ('block', 'block'), ('pavement', 'pavement'), ('pillar', 'pillar'), ('pestle', 'pestle'), ('parapet', 'parapet'), ('weight', 'weight'), ('jamb', 'jamb'), ('well_curb', 'well curb'), ('rock_face', 'rock face'), ('seat', 'seat'), ('tombstone_barrel_shaped', 'tombstone, barrel-shaped'), ('sphere', 'sphere'), ('seal_to_affirm_attach', 'seal to affirm/attach'), ('seal_to_impress_on_collyria', 'seal to impress on collyria'), ('statue_of_a_god', 'statue of a god'), ('flint', 'flint'), ('mirror', 'mirror'), ('statue', 'statue'), ('plaque_stela', 'plaque/stela'), ('furniture', 'furniture'), ('slab', 'slab'), ('gameboard', 'gameboard'), ('sales_ticket', 'sales ticket'), ('tile', 'tile'), ('gaming_die', 'gaming die'), ('token_pseudo_currency', 'token, pseudo-currency'), ('gaming_token', 'gaming token'), ('token_for_building_inauguration', 'token, for building inauguration'), ('token_for_spectacles', 'token, for spectacles'), ('container', 'container'), ('bell', 'bell'), ('support', 'support'), ('pipe', 'pipe'), ('vessel', 'vessel'), ('cooking_vessel', 'cooking vessel'), ('tableware', 'tableware'), ('capital_echinus', 'capital, echinus'), ('capital_abacus', 'capital, abacus'), ('cinerary_urn_case', 'cinerary urn case'), ('cinerary_urn_lid', 'cinerary urn lid'), ('honorary_shield', 'honorary shield'), ('building', 'building'), ('burial_building', 'burial building'), ('column_shaft_lower', 'column shaft, lower'), ('column_shaft_upper', 'column shaft, upper'), ('tablet_with_moneyor_s_inspection_annotations', 'tablet with moneyor’s inspection annotations'), ('inscribed_slab_relating_to_the_administration_of_the_annona', 'inscribed slab relating to the administration of the annona'), ('tax_exemption_tablet', 'tax exemption tablet'), ('slab_with_imperial_constitution_for_discharged_soldiers', 'slab with imperial constitution for discharged soldiers'), ('hospitability_tablet', 'hospitability_tablet'), ('slab_with_an_act_of_patronage', 'slab with an act of patronage'), ('curse_tablet', 'curse tablet'), ('columbarium_slab_niche', 'columbarium slab/niche'), ('podium_table', 'podium table'), ('sarcophagus_case', 'sarcophagus case'), ('sarcophagus_lid', 'sarcophagus lid'), ('work_instrument_any_type', 'work instrument, any type'), ('unknown', 'unknown')], max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='epigraphy',
            name='promoter',
            field=models.CharField(blank=True, choices=[('venetian_aristocrat', 'Venetian aristocrat'), ('venetian_state', 'Venetian State'), ('cypriot', 'Cypriot')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='epigraphy',
            name='state_of_preservation',
            field=models.CharField(blank=True, choices=[('complete', 'complete'), ('probably_complete', 'probably complete'), ('broken', 'broken'), ('incomplete', 'incomplete'), ('epigraphic_fragments_contiguous_so_as_to_allow_joining', 'epigraphic fragments, contiguous so as to allow joining'), ('epigraphic_fragments_belonging_to_different_areas_of_the_same_inscription_but_not_joining', 'epigraphic fragments belonging to different areas of the same inscription, but not joining'), ('epigraphic_fragments_which_can_be_only_partly_joined', 'epigraphic fragments, which can be only partly joined')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='epigraphy',
            name='type_of_inscription',
            field=models.CharField(blank=True, choices=[('religious', 'Religious'), ('honorary', 'Honorary'), ('funerary', 'Funerary'), ('building_public_or_private', 'Building, public or private'), ('law_official_text', 'Law/official text'), ('unknown', 'Unknown')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='epigraphy',
            name='type_of_writing',
            field=models.CharField(blank=True, choices=[('inked', 'inked'), ('engraved', 'engraved'), ('inlaid_or_embossed', 'inlaid or embossed'), ('damascened', 'damascened'), ('channelled', 'channelled'), ('metal_letters_applied', 'metal letters applied'), ('relief', 'relief'), ('moulded', 'moulded'), ('scratched', 'scratched'), ('painted', 'painted'), ('impressed_dots', 'impressed dots'), ('incised', 'incised'), ('impressed', 'impressed'), ('inscribed_on_a_soft_surface', 'inscribed on a soft surface'), ('perforated', 'perforated'), ('mosaic', 'mosaic'), ('punched', 'punched'), ('other', 'other'), ('unknown', 'unknown')], max_length=200, null=True),
        ),
    ]
