# Generated by Django 4.0.4 on 2024-07-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epigraphy', '0006_alter_epigraphy_administrative_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epigraphy',
            name='current_location',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='epigraphy',
            name='motivation',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='epigraphy',
            name='past_location',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
