# Generated by Django 4.0.4 on 2024-09-23 11:33

from django.db import migrations, models
import epigraphy.models
import storages.backends.s3


class Migration(migrations.Migration):

    dependencies = [
        ('epigraphy', '0007_alter_epigraphy_current_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monument',
            name='site_image',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to=epigraphy.models.photos),
        ),
        migrations.AlterField(
            model_name='epigraphy',
            name='type_of_inscription',
            field=models.CharField(blank=True, choices=[('religious', 'Religious'), ('honorary', 'Honorary'), ('funerary', 'Funerary'), ('Building_public_or_private', 'Building, public or private'), ('law_official_text', 'Law/official text'), ('unknown', 'Unknown')], max_length=100, null=True),
        ),
    ]
